### ISSUE TITLE
update 0.2.0

### ISSUE THREAD

**Issue by fastoslinux** [flathub/com.valvesoftware.Steam.VulkanLayer.MangoHud#2]
https://github.com/flightlessmango/MangoHud/releases/tag/v0.2.0

**Comment by gasinvein** [comment]
It's already 0.2.0, or what's your issue about?
https://github.com/flathub/com.valvesoftware.Steam.VulkanLayer.MangoHud/blob/0d7da72d212d4120a670263d56e934fb7bc4aa50/com.valvesoftware.Steam.VulkanLayer.MangoHud.yml#L26-L29

**Comment by fastoslinux** [comment]
no issue, tnks
