### ISSUE TITLE
Normal Usage As Per MangoHud's instructions

### ISSUE THREAD

**Issue by ghost** [flathub/com.valvesoftware.Steam.VulkanLayer.MangoHud#5]
At this moment the HUD is only functional with games that utilize the Vulkan API, as the `MANGOHUD=1` shell variable is the only working way of enabling it in the Steam Flatpak.

https://github.com/flightlessmango/MangoHud#normal-usage

I've tried to append a full path to the launch options, but it didn't work; I'm probably missing something.

**Comment by gasinvein** [comment]
Waiting for flathub/flathub#1413 to be merged. Once it is, the extension point will change and `mangohud` command will be available.

**Comment by gasinvein** [comment]
@Bryophyllum We have a a problem with EOL'ing this extension flathub/flathub#1419, you may need to uninstall `.VulkanLayer.MangoHud` and install `.Utility.MangoHud` manually for now.
